### ISSUE TITLE
Zoro official rebranding to AniWatch

### ISSUE THREAD

**Issue by nisheet-n** [consumet/consumet.ts#354]
### Source name

AniWatch

### Source link

https://aniwatch.to

### Language

English

### Source type

Anime

### Additional info

Zoro.to is now AniWatch.to. Please update all the Zoro instances to AniWatch.

**Comment by Eltik** [comment]
Thanks for opening an issue! The domain doesn’t really matter however for Zoro. I have a separate API I’ve made that just uses Zoro and the code works fine since it auto-redirects. Note though that Zoro has changed their way of fetching sources which will likely be fixed in another commit/pull request.

**Comment by nisheet-n** [comment]
Thanks for the quick response. Yeah, it auto-redirects for now, but when their rebranding process is done, I guess it wont. I opened this so that when it happens in the near future, the API won't break.
Thanks!

**Comment by ghoshRitesh12** [comment]
So I checked right now, and the api is not working for zoro.

**Comment by nisheet-n** [comment]
Yep they removed the auto-redirecting thing. Please update.

**Comment by ghoshRitesh12** [comment]
> Yep they removed the auto-redirecting thing.

I have a different api that scrapes zoro content which I made for fun, I just changed the baseUrl, but its working there on my api. For consumet zoro's base url have been changed, but its still returning an empty object
