### ISSUE TITLE
cannot fetch episodes sources in gogoanime.

### ISSUE THREAD

**Issue by regisx001** [consumet/consumet.ts#515]
### Describe the bug

cannot fetch episodes sources in gogoanime.

### Steps to reproduce

SOME

### Expected behavior

S

### Actual behavior

S

### Additional context

fetchEpisodeSources() function not working due a CORS ERROR .

**Comment by NanotechPikachu** [comment]
Are you trying to access this using a website? The CORS error can be rectified in the back end by adding header 
Refer [this](https://www.bannerbear.com/blog/what-is-a-cors-error-and-how-to-fix-it-3-ways/)

I also experienced the same error but since mine was the next app, i rectified by converting the page from client to server.

**Comment by regisx001** [comment]
aha , ok .
this is right i trying access it using a website, but i found another solution using another api .
thanks for help !!!
