### ISSUE TITLE
Getting empty data on Zoro & other providers

### ISSUE THREAD

**Issue by Subhajeetch** [consumet/consumet.ts#623]
### Describe the bug

I'm unable to fetch streaming links data, it was working pretty well yesterday. I checked today it doesn't working. I don't know what's wrong maybe I should wait or I could really use an explanation right now.

### Steps to reproduce

![Screenshot_20241211-004412](https://github.com/user-attachments/assets/85ca2c09-ae39-496b-826e-f70d343a6f2b)
Getting empty data like this.... 

I asked chatgpt with the megacloud extractor code, 
It says this:
"If MegaCloud updates its encryption or script logic, parts of this extractor may break.
Reliance on regex for variable extraction can be fragile."

If thats the case, I hope it'll be fixed soon!

### Expected behavior

**## It was giving me complete data like this:**
{
  "headers": {
      "Referer": "string",
      "watchsb": "string",
      "User-Agent": "string"
  },
  "sources": [
      {
      "url": "string",
      "quality": "string",
      "isM3U8": true
      }
  ]
}

### Actual behavior

**## Its giving empty structures like this:**

{
  "sources": [],
  "subtitles": []
}

### Additional context

Anyways, thank you so much for making this possible. Appreciate it!!!!

**Comment by LakshmanSagar** [comment]
Same issue 😓

E  Error fetching streaming URLs     java.lang.Exception: No streams available

**Comment by itz-ankit** [comment]
Same here as well

**Comment by itz-ankit** [comment]
> Hope they update it soon :/

Really hope so :')
or else my website is dead 
https://doki-watch.netlify.app

**Comment by JabolDev** [comment]
upon analyzing the issue, it seems this https://github.com/consumet/consumet.ts/blob/dcf16697e088f94f7e4e1876f7815eb18d409d9e/src/extractors/megacloud.ts#L47

are returning empty objects instead of returning the encrypted sources.
they probably changed or add some client verification when loading the getsource link.

**Comment by Subhajeetch** [comment]
@JabolDev New decryption methods has to be applied right? Any idea?

**Comment by Subhajeetch** [comment]
@riimuru sorry to disturb siree, we all left hanging:/ hoping to get this thing fixed. Thank you for your hard work!

**Comment by Daxterapid** [comment]
yep, megacloud changed the parameters to the getSources route. I don't know much about reverse engineering but I took a crack at it, maybe this will help if anyone else wants to give it a shot

the parameters to getSources are now `id`, `v`, `h`, `b`, and they come from these script variables:
`id`: `window.pid`
`v`: `window.localStorage.kversion || window.browser_version`
`h`: `window.localStorage.kid || ''`
`b`: `window.browser_version`

`window.pid` is a 104-character alphanumeric string which unfortunately comes from a wasm module (`megacloud.tv/images/loading.png?v=0.0.9`) so I don't how it gets calculated
`window.localStorage.kversion` (an integer) and `window.localStorage.kid` (a 20-byte/40-character hex string) also come from the wasm module
`window.browser_version`, a 32-bit uint is an integer whose upper 24 bits are flags representing specific browser capabilities:

- bit 31: document.createElement('9cbc1d63ef40c79') is non-null
- bit 30: getContext method exists on a canvas
- bit 29: window.WebSocket exists
- bit 28: document.$cdc_asdjflasutopfhvcZLmcfl_ exists
- bit 27: window.GPU exists
- bit 26: window.webkitMediaStream exists
- bit 25: window.RTCPeerConnection exists
- bit 24: window.RTCDataChannel exists
- bit 23: getContext('webgl') returns non-null on a canvas
- bit 22: window.WebGLActiveInfo exists
- bit 21: window.WebAssembly exists
- bit 20: WebAssembly.instantiate method exists
- bit 19: window.mdn exists
- bit 18: window.chrome exists
- bit 17: window.documentPictureInPicture exists
- bit 16: WebAssembly.module exists
- bit 15: window.Audio exists
- bit 14: window.CanvasGradient exists
- bit 13: window.document exists
- bit 12: window.navigator exists
- bit 11: navigator.userAgentData exists
- bit 10: navigator.userAgentData.mobile == 1
- bit 9: navigator.appCodeName is "Mozilla"
- bit 8: major version of the user agent is less than 100

bits 0-7 are 0
example: `0b011010111111000111110010_00000000` -> `1811018240`

all of `id`, `v`, and `h` seem to change randomly, but will `v` and `h` will occasionally have repeat values. `v` and `h` afaik are linked in change and `id` is separate
one thing I noticed about the `id` parameter is that while the last 78 digits are always different, but the first 26 digits occasionally repeat, and the very last digit with it
since the `id` parameter before this change was just the embed id, the new `id` parameter is probably the embed id encrypted using `v`, `h`, and `b`
all the parameters also expire, so maybe they're generated based on a timestamp or a changing variable when you initially fetch the embed page?

**Comment by Subhajeetch** [comment]
Damn...
I even mentioned the guy who made last commit on the megacloud.ts seems like busy :( let's see

**Comment by Andro999b** [comment]
You can decompile wasm module to c-like code with https://github.com/WebAssembly/wabt.

**Comment by animegers** [comment]
Full stack DEVs are out only hope, i was a broken dev when gogos vidstream servers were up and running... fixed the api more than 20 times myself. It was easy and easily understandable but megacloud.tv just ripps my brain..

**Comment by JabolDev** [comment]
this is already fix, i wonder where they going to patch consumet.

**Comment by Daxterapid** [comment]
implementation details: https://github.com/ghoshRitesh12/aniwatch/compare/76a48c7..3a827cf
